- name: Gather facts of remote host
  ansible.builtin.setup:
    gather_subset: all

- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev', 'python3-setuptools', 'python3-pip', 'python3-venv', 'python-docker', 'git', 'vim']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  ansible.builtin.pip:
    name: ['pip', 'openstacksdk']
    state: latest
