- hosts: couchdbnodes
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true
  roles:
    - role: couchdb-container

- hosts: couchdbnodes:!couchdbmasternode
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true
  roles:
    - role: couchdb-cluster
