- hosts: instances
  vars_files:
    - host_vars/volume.yaml
  gather_facts: false
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: /Users/gray/group-8.pem
    - ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
    - role: mount-volumes