---
- name: Start a couchdb container
  become: yes
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    env:
      COUCHDB_USER: "{{ user }}"
      COUCHDB_PASSWORD: "{{ password }}"
      NODENAME: "{{ inventory_hostname }}"
      COUCHDB_SECRET: "{{ cookie }}"
      ERL_FLAGS: "-setcookie \"{{ cookie }}\" -name \"couchdb@{{ inventory_hostname }}\""
      COUCHDB_ERLANG_COOKIE: "{{ cookie }}"

