- name: Start a couchdb container
  become: yes
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    env:
      COUCHDB_USER: "{{ user }}"
      COUCHDB_PASSWORD: "{{ password }}"
      COUCHDB_SECRET: "{{ cookie }}"
